camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: admin
    filter:
      create: All tasks
    deployment-resource-pattern: classpath*:**/*.bpmn, **/*.dmn, **/*.cmmn
    generic-properties:
      properties:
        # cleanup was not tested...
        historyTimeToLive: 5
        historyCleanupStrategy: removalTimeBased
        historyRemovalTimeStrategy: end
        historyCleanupBatchSize: 200
        historyCleanupBatchWindowStartTime: 02:15
        historyCleanupBatchWindowEndTime: 02:45



