camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: admin
    filter:
      create: All tasks
    deployment-resource-pattern: classpath*:**/*.bpmn, **/*.dmn, **/*.cmmn
